### ISSUE TITLE
3.9  - something missing

### ISSUE THREAD

**Issue by venomega** [srevinsaju/pyappimage#2]
is there something missing on appimage file?

```
[root@aincrad a]# ls
pyappimage  pyappimage-3.8-x86_64.AppImage  setup.py                                 up.
[root@aincrad a]# ./pyappimage-3.8-x86_64.AppImage build
Warning: No icon file was provided. The default Python icon will be used. To add an icon, place a auntnee.svg or auntnee.png in pyappimage
Warning: No Appdata file provided. Please add pyappimage/auntnee.appdata.xml for desktop integration, and indexing.
fusermount detected on host system.
⠙ Building AppImage for auntneeTraceback (most recent call last):
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/bin/pyappimage", line 9, in <module>
    sys.exit(cli())
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/site-packages/pyappimage/cli.py", line 211, in build
    pyappimage_build(config, appdata=appdata, icon=icon_path,
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/site-packages/pyappimage/build/build.py", line 207, in build
    install_packages(setup_py=setup_py, build_directory=build_directory)
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/site-packages/pyappimage/build/build.py", line 130, in install_packages
    _pip_install_proc = subprocess.run(_(
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/tmp/.mount_pyappirn7Rmm/opt/python3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.mount_pyappirn7Rmm/opt/python3.8/bin/pip'
[root@aincrad a]# 

```

**Comment by srevinsaju** [comment]
Thanks for reporting the error. I found the cause of it. Meanwhile, you can still use `pyappimage` on `python3.9` by 
```bash
pip3 install https://github.com/srevinsaju/pyappimage/archive/master.tar.gz

# and then
pyappimage build
```
